-- TPF Communication Training — full seed (Postgres)
-- Paste this into Supabase SQL Editor and click Run.

DROP TABLE IF EXISTS evaluations CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS password_resets CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS scenarios CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR UNIQUE NOT NULL,
  password_hash VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  role VARCHAR DEFAULT 'employee',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX ix_users_email ON users(email);

CREATE TABLE scenarios (
  id SERIAL PRIMARY KEY,
  message TEXT NOT NULL,
  sender_name VARCHAR,
  role_applied VARCHAR,
  company_name VARCHAR,
  tone VARCHAR,
  category VARCHAR,
  situation_type VARCHAR,  
  expected_points JSONB,
  ideal_response_tone TEXT,
  difficulty VARCHAR DEFAULT 'medium',
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE sessions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  scenario_id INTEGER NOT NULL REFERENCES scenarios(id),
  date DATE NOT NULL,
  status VARCHAR DEFAULT 'active',
  message_count INTEGER DEFAULT 0,
  daily_summary TEXT,
  overall_score FLOAT,
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT uq_user_date UNIQUE (user_id, date)
);

CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id),
  role VARCHAR NOT NULL,
  content TEXT NOT NULL,
  sequence_num INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE evaluations (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id),
  message_id INTEGER NOT NULL REFERENCES messages(id),
  acknowledge FLOAT DEFAULT 0,
  apology FLOAT DEFAULT 0,
  clarity FLOAT DEFAULT 0,
  reassurance FLOAT DEFAULT 0,
  overall FLOAT DEFAULT 0,
  decision VARCHAR,
  ai_reply TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE password_resets (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  token VARCHAR UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX ix_password_resets_user_id ON password_resets(user_id);
CREATE INDEX ix_password_resets_token ON password_resets(token);

-- Users
INSERT INTO users (email, password_hash, name, role) VALUES ('abhay@theproductfolks.com', '$2b$12$k7u2mAUdvZi8BMMj/SsfDuYUPlVpvNfYoC.Kls8sylgVijX9mZod6', 'Abhay', 'admin');
INSERT INTO users (email, password_hash, name, role) VALUES ('test@1234', '$2b$12$y0ltWuazYkevwvW.JBU38epLA5r5o7odOgFFfqbvz46.dWSP6ISJm', 'Test User', 'employee');

-- Scenarios (56 rows)
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi there, I applied for the Senior Product Manager role at Swiggy a few weeks back, but I haven''t heard anything yet. I''m really excited about this opportunity and just wanted to check in on the status of my application. I hope to hear from you soon!', 'Ananya', 'Senior Product Manager', 'Swiggy', 'concerned_candidate', 'delay', 'no_update_after_applying', '["acknowledge", "show_empathy", "reassure", "provide_timeline"]'::jsonb, 'Thank you for reaching out, Ananya! We appreciate your patience, and we''re currently reviewing applications; you’ll hear from us shortly.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello! I applied for the Product Manager position at Zomato about three weeks ago, and I haven''t received any updates yet. I’m really passionate about this role, and I’d love to know where I stand. Any news would be greatly appreciated!', 'Rohit', 'Product Manager', 'Zomato', 'concerned_candidate', 'delay', 'no_update_after_applying', '["acknowledge", "apologize", "clarify", "set_expectations", "show_empathy"]'::jsonb, 'Hi Rohit, thank you for your interest! We truly value your enthusiasm and will update you on your application status as soon as possible.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi, I submitted my application for the Associate PM role at Paytm around two weeks ago and haven’t heard back yet. I’m really eager to join the team and would appreciate any updates you might have!', 'Priya', 'Associate PM', 'Paytm', 'concerned_candidate', 'delay', 'no_update_after_applying', '["acknowledge", "apologize", "reassure", "explain_process"]'::jsonb, 'Thanks for checking in, Priya! We’re actively reviewing candidates and will get back to you soon.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey there! I applied for a Growth PM position at BharatPe around 10 days ago and I’m starting to feel a bit anxious about the wait. I’d really love to know if there are any updates on my application—I’m super excited about this opportunity!', 'Vikram', 'Growth PM', 'BharatPe', 'concerned_candidate', 'delay', 'no_update_after_applying', '["acknowledge", "apologize", "show_empathy", "clarify"]'::jsonb, 'Hi Vikram! We understand the anticipation and appreciate your excitement; we’ll keep you posted on your application status soon.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi, I hope you’re doing well! I applied for the Product Manager role at Meesho about three weeks ago, but I haven’t received any feedback yet. I’m really looking forward to contributing to the team, so any updates would mean a lot!', 'Sneha', 'Product Manager', 'Meesho', 'concerned_candidate', 'delay', 'no_update_after_applying', '["acknowledge", "show_empathy", "provide_timeline", "reassure"]'::jsonb, 'Thank you, Sneha! We’re thrilled about your interest and will update you on your application process shortly.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF team, I hope you''re doing well. It''s been almost two weeks since my last interview for the Senior PM role at Zepto, and I haven''t heard back yet. I’m getting a bit anxious and would really appreciate any update you might have.', 'Arjun', 'Senior PM', 'Zepto', 'frustrated_candidate', 'delay', 'post_interview_silence', '["acknowledge", "show_empathy", "provide_timeline", "reassure"]'::jsonb, 'We''re on it, Arjun! We''ll check in with Zepto and get back to you shortly — your patience is much appreciated!', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team, I hope all is well. I wanted to reach out because it''s been over a week since my interview for the Product Manager position at CRED, and I''m still waiting for feedback. It’s making me a bit anxious, and I''d love to hear any updates you might have.', 'Sneha', 'Product Manager', 'CRED', 'frustrated_candidate', 'delay', 'post_interview_silence', '["acknowledge", "apologize", "show_empathy", "explain_process"]'::jsonb, 'Thanks for your patience, Sneha! We''ll reach out to CRED for an update and let you know as soon as we hear back.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF, I hope you’re doing great. I’m reaching out because it’s been almost two weeks since my interview for the Principal PM role at Razorpay. I’m eager to hear back and just wanted to check if you have any updates.', 'Ravi', 'Principal PM', 'Razorpay', 'frustrated_candidate', 'delay', 'post_interview_silence', '["acknowledge", "reassure", "set_expectations", "clarify"]'::jsonb, 'Hi Ravi! We''re in touch with Razorpay and will ensure you get an update soon — hang tight!', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I hope you''re all doing well. I wanted to follow up on my recent interview for the Product Manager position at Google. It’s been over a week and I haven’t received any feedback yet. I would really appreciate any updates!', 'Anjali', 'Product Manager', 'Google', 'frustrated_candidate', 'delay', 'post_interview_silence', '["acknowledge", "show_empathy", "clarify", "provide_timeline"]'::jsonb, 'Thanks for reaching out, Anjali! We''ll check in with Google and update you ASAP — your enthusiasm is appreciated!', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi there TPF team, just wanted to touch base regarding my application for the Senior PM role at PhonePe. It’s been about two weeks since my last interview, and I''m starting to feel a bit anxious. Any updates would be greatly appreciated!', 'Karan', 'Senior PM', 'PhonePe', 'frustrated_candidate', 'delay', 'post_interview_silence', '["acknowledge", "apologize", "reassure", "show_empathy"]'::jsonb, 'Hi Karan! We completely understand your concern and will follow up with PhonePe for an update shortly — thanks for your patience!', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF Team, I hope you’re doing well! I wanted to reach out because I’ve just received an offer from Zomato and they need a decision from me by tomorrow. I’m really excited about the role I applied for with you, but I’m feeling a bit pressured to respond to Zomato. Can you please let me know the status of my application? Thanks a lot!', 'Ananya', 'Product Manager', 'Zomato', 'concerned_candidate', 'offer_issue', 'competing_offer_urgency', '["acknowledge", "show_empathy", "provide_timeline", "reassure"]'::jsonb, 'We understand your urgency, Ananya, and will prioritize your application to provide an update as soon as possible!', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF, I wanted to give you a quick heads-up that I''ve been offered a Senior PM position at Swiggy, and I need to give them an answer soon. I’m really passionate about the opportunity with your community, and I’d love to know where I stand in your hiring process. Thank you for your support!', 'Rahul', 'Senior PM', 'Swiggy', 'concerned_candidate', 'offer_issue', 'competing_offer_urgency', '["apologize", "clarify", "explain_process", "set_expectations"]'::jsonb, 'Thanks for letting us know, Rahul! We''ll expedite your application review and keep you posted on our next steps.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF Team, I hope you’re all doing great! I’m in a bit of a bind as I''ve just received a job offer from Meesho and they’ve given me a tight deadline to respond. I’m really hoping to hear back from you soon about my application because I feel a strong fit for the Product Manager role. Appreciate your help!', 'Priya', 'Product Manager', 'Meesho', 'concerned_candidate', 'offer_issue', 'competing_offer_urgency', '["acknowledge", "reassure", "provide_timeline", "show_empathy"]'::jsonb, 'We totally understand, Priya! We’ll work quickly to provide you with an update on your application status.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi Team, I hope everything is going well! I wanted to reach out because I just got an offer from Paytm, and they need to hear back from me by tomorrow. I’m really interested in the position I applied for with you, so I’d appreciate any updates on my application status. Thank you for your understanding!', 'Karan', 'Growth PM', 'Paytm', 'concerned_candidate', 'offer_issue', 'competing_offer_urgency', '["show_empathy", "acknowledge", "clarify", "set_expectations"]'::jsonb, 'Thanks for updating us, Karan! We’ll fast-track your application review and keep you informed of any developments.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team! I clicked ''Get Referred'' for the Associate PM role at Razorpay but I''m a bit lost on what happens next. It’s been a few days, and I haven’t heard anything. Can you please help me understand the process? Thanks!', 'Riya Sharma', 'Associate PM', 'Razorpay', 'confused_candidate', 'process_confusion', 'referral_process_confusion', '["acknowledge", "clarify", "reassure", "explain_process", "set_expectations"]'::jsonb, 'We''re here to help, Riya! We''ll check on the referral status and get back to you shortly with an update.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team! I applied for the Product Manager position at BharatPe and clicked on ''Get Referred'' last week, but I haven’t received any updates yet. Could you please let me know what the next steps are? I really appreciate it!', 'Ajay Verma', 'Product Manager', 'BharatPe', 'confused_candidate', 'process_confusion', 'referral_process_confusion', '["acknowledge", "apologize", "reassure", "provide_timeline", "show_empathy"]'::jsonb, 'Hi Ajay! Thanks for reaching out — I’ll follow up on your referral and ensure you have the info you need soon!', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF, I clicked ''Get Referred'' for the Associate PM role at Pine Labs, but I haven''t heard back yet and I’m feeling a bit anxious. Can you guide me on what to expect moving forward? Thank you so much!', 'Sneha Patel', 'Associate PM', 'Pine Labs', 'confused_candidate', 'process_confusion', 'referral_process_confusion', '["acknowledge", "clarify", "explain_process", "reassure", "set_expectations"]'::jsonb, 'Hi Sneha! No worries, we’re on it! I’ll check your referral status and keep you in the loop shortly.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey there, TPF team! I recently clicked ''Get Referred'' for a Product Manager position at Pocket FM, but I’m not sure what the next steps are. I’d love some clarity on this! Thanks a ton!', 'Karan Singh', 'Product Manager', 'Pocket FM', 'confused_candidate', 'process_confusion', 'referral_process_confusion', '["acknowledge", "clarify", "explain_process", "reassure", "show_empathy"]'::jsonb, 'Hi Karan! Absolutely, I’ll dig into your referral and get back to you with all the details soon.', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF team! I’m really excited about the offer I accepted for the Senior PM role at Zepto a couple of weeks ago, but I still haven’t received the formal offer letter. I’m getting a bit anxious and would love to know if there’s any update on this. Thanks for your help!', 'Riya Sharma', 'Senior PM', 'Zepto', 'concerned_candidate', 'offer_issue', 'offer_letter_delay', '["acknowledge", "show_empathy", "clarify", "provide_timeline"]'::jsonb, 'We appreciate your patience, Riya! We''ll check in with Zepto and get back to you shortly.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team! I hope you’re doing well. I accepted the offer for the Product Manager position at CRED about two weeks ago, but I haven''t seen the formal offer letter yet. Can you please help me understand what’s happening? I’m really eager to get started!', 'Aarav Gupta', 'Product Manager', 'CRED', 'concerned_candidate', 'offer_issue', 'offer_letter_delay', '["acknowledge", "reassure", "show_empathy", "explain_process"]'::jsonb, 'Thanks for reaching out, Aarav! We''ll follow up with CRED and keep you posted on the status.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I’m really looking forward to joining Swiggy as a Senior PM! I accepted the offer verbally about a week and a half ago, but I''m still waiting on the official offer letter. Is there any update you can share? I really want to start preparing for my new role!', 'Sneha Patel', 'Senior PM', 'Swiggy', 'concerned_candidate', 'offer_issue', 'offer_letter_delay', '["acknowledge", "apologize", "clarify", "set_expectations"]'::jsonb, 'Hi Sneha! We understand your eagerness and will check with Swiggy about your offer letter right away.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF team! I hope all is well. I verbally accepted the Product Manager role at PhonePe two weeks ago, and I’m still waiting on the formal offer letter. I’m starting to get a bit worried. Can you help me find out what the delay is?', 'Lakshya Mehta', 'Product Manager', 'PhonePe', 'concerned_candidate', 'offer_issue', 'offer_letter_delay', '["acknowledge", "reassure", "explain_process", "provide_timeline"]'::jsonb, 'Thanks for your patience, Lakshya! We will reach out to PhonePe and update you as soon as possible.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi team, I hope you’re doing well. I recently learned that my application for the Senior PM role at Google was unsuccessful, and I’d really appreciate it if you could share some specific feedback on my interview. I’m eager to improve and would love any insights you could provide. Thanks so much!', 'Rahul Sharma', 'Senior PM', 'Google', 'concerned_candidate', 'feedback_request', 'rejection_feedback_request', '["show_empathy", "reassure", "explain_process", "acknowledge"]'::jsonb, 'We appreciate your proactive approach, Rahul! We''ll gather feedback and share it with you soon to support your growth.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I wanted to reach out regarding my application for the Principal PM position at Razorpay. I was quite disappointed to hear I didn’t make it, and I would be grateful if you could provide some feedback on my performance. It would really help me in my future applications. Thank you!', 'Sneha Desai', 'Principal PM', 'Razorpay', 'concerned_candidate', 'feedback_request', 'rejection_feedback_request', '["acknowledge", "provide_timeline", "clarify", "show_empathy"]'::jsonb, 'Thank you for reaching out, Sneha! We’re here to help and will follow up with detailed feedback shortly.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi there! I hope you’re doing great. I found out that my application for the Product Manager role at CRED didn’t go through, and I’m quite curious about the reasons. A bit of feedback would mean a lot as I’d love to learn and improve. Thanks for your help!', 'Amit Verma', 'Product Manager', 'CRED', 'concerned_candidate', 'feedback_request', 'rejection_feedback_request', '["explain_process", "reassure", "set_expectations", "show_empathy"]'::jsonb, 'Hi Amit! We appreciate your enthusiasm and will provide you with feedback soon to help you in your journey.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I hope you’re all well! I’m reaching out as I was recently informed that my application for the Senior PM role at BharatPe was not successful. I’d love to understand what areas I could improve upon. Any specific feedback would be incredibly helpful. Thank you!', 'Priya Nair', 'Senior PM', 'BharatPe', 'concerned_candidate', 'feedback_request', 'rejection_feedback_request', '["acknowledge", "clarify", "show_empathy", "provide_timeline"]'::jsonb, 'Thanks for your message, Priya! We’re committed to your growth and will send over detailed feedback for you soon.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF team, I just saw that my interview with Meesho was canceled without any notice or reason. I''m feeling pretty disappointed, especially after preparing so much for it. Can you please help me understand what''s going on?', 'Riya', 'Product Manager', 'Meesho', 'frustrated_candidate', 'process_confusion', 'interview_cancelled_no_reschedule', '["acknowledge", "apologize", "clarify", "show_empathy"]'::jsonb, 'We understand your frustration, Riya, and we''re here to help you through this process.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I just received a notification that my interview with Zomato has been canceled unexpectedly. I was really looking forward to it and I''m quite uncertain about what to do next. Any insights would be appreciated!', 'Ayaan', 'Senior PM', 'Zomato', 'frustrated_candidate', 'process_confusion', 'interview_cancelled_no_reschedule', '["acknowledge", "apologize", "explain_process", "reassure"]'::jsonb, 'We''re sorry for this unexpected situation, Ayaan, and we''ll find out more information for you as quickly as possible.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team, I just found out that my interview with Pine Labs has been canceled without any explanation. It''s really disheartening, and I would love to know what happened. Thanks for your help!', 'Neha', 'Product Manager', 'Pine Labs', 'frustrated_candidate', 'process_confusion', 'interview_cancelled_no_reschedule', '["acknowledge", "apologize", "show_empathy", "set_expectations"]'::jsonb, 'We completely empathize with your disappointment, Neha, and we''re committed to finding a resolution for you.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF team, I just received a message that my interview with Paytm was canceled, and there was no follow-up. I''m feeling quite lost about what to do next and would appreciate any guidance you can provide.', 'Raj', 'Senior PM', 'Paytm', 'frustrated_candidate', 'process_confusion', 'interview_cancelled_no_reschedule', '["acknowledge", "apologize", "clarify", "reassure", "show_empathy"]'::jsonb, 'We''re here for you, Raj, and we''ll make sure to get the necessary updates on this situation for you.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team, I hope everything is alright! I was really excited about the Growth PM position at Swiggy, but I haven''t heard back in a while. Just wanted to check in and see if there are any updates. Thanks!', 'Aarav', 'Growth PM', 'Swiggy', 'ghosted_candidate', 'ghosting', 'ghosted_mid_process', '["acknowledge", "apologize", "clarify", "show_empathy", "set_expectations"]'::jsonb, 'We appreciate your patience and will get back to you with updates shortly!', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF, I hope you''re doing well! I was really looking forward to hearing back about the Associate PM role at BharatPe. It’s been a bit quiet, and I''m just wondering if there''s any news on my application. Thanks for your help!', 'Simran', 'Associate PM', 'BharatPe', 'ghosted_candidate', 'ghosting', 'ghosted_mid_process', '["acknowledge", "apologize", "reassure", "show_empathy", "provide_timeline"]'::jsonb, 'Thanks for reaching out! We understand the wait can be tough, and we’ll update you soon!', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I hope all is well! I’m just checking in about my application for the Senior PM role at Zepto. It''s been a little while since we last spoke, and I''m eager for any updates. Appreciate your assistance!', 'Riya', 'Senior PM', 'Zepto', 'ghosted_candidate', 'ghosting', 'ghosted_mid_process', '["acknowledge", "apologize", "explain_process", "reassure", "set_expectations"]'::jsonb, 'Thanks for your patience! We will reach out with updates very soon.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF, just wanted to follow up about my application for the Growth PM position at Razorpay. I haven’t heard back in a while and I''m feeling a bit anxious about it. Would love to know if there’s any progress. Thanks a lot!', 'Vikram', 'Growth PM', 'Razorpay', 'ghosted_candidate', 'ghosting', 'ghosted_mid_process', '["acknowledge", "apologize", "clarify", "show_empathy", "provide_timeline"]'::jsonb, 'Thanks for reaching out! We genuinely appreciate your interest and will update you shortly.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team, I just received the offer from CRED, but the salary is way lower than what we discussed initially. I’m feeling pretty confused and a bit undervalued right now. Can you help me understand what''s going on?', 'Rahul', 'Senior PM', 'CRED', 'frustrated_candidate', 'offer_issue', 'salary_mismatch', '["acknowledge", "clarify", "show_empathy", "set_expectations"]'::jsonb, 'Absolutely, we understand your concerns and will reach out to CRED to clarify the situation as soon as possible.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi team, I just got an offer from PhonePe, but the salary is much lower than what we talked about. Honestly, it''s a bit disheartening. Could you please look into this for me?', 'Ananya', 'Product Manager', 'PhonePe', 'frustrated_candidate', 'offer_issue', 'salary_mismatch', '["acknowledge", "apologize", "explain_process", "reassure"]'::jsonb, 'We hear you, Ananya, and we''re on it! We''ll reach out to PhonePe to address this discrepancy right away.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF, I’m really surprised by the offer from Meesho because the salary doesn’t match what we discussed during the interviews. I’m feeling a bit let down. Can you assist me in resolving this?', 'Siddharth', 'Principal PM', 'Meesho', 'frustrated_candidate', 'offer_issue', 'salary_mismatch', '["acknowledge", "show_empathy", "provide_timeline", "clarify"]'::jsonb, 'Thanks for bringing this to our attention, Siddharth; we''ll promptly reach out to Meesho to find out what happened and keep you updated.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi there, I just received an offer from Pine Labs, but the salary is significantly lower than what we had discussed. It’s quite disappointing, and I’m hoping you can help me figure this out.', 'Priya', 'Senior PM', 'Pine Labs', 'frustrated_candidate', 'offer_issue', 'salary_mismatch', '["acknowledge", "show_empathy", "set_expectations", "clarify"]'::jsonb, 'We completely understand your frustration, Priya, and we’ll dive into this with Pine Labs to get clarity on the offer immediately.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team, I just noticed that the Product Manager position at Zomato I applied for is no longer on the job board. I''m feeling really confused and worried about what this means for my application. Can you please clarify what''s going on?', 'Aarav', 'Product Manager', 'Zomato', 'confused_candidate', 'process_confusion', 'role_no_longer_listed', '["acknowledge", "apologize", "clarify", "reassure", "show_empathy"]'::jsonb, 'We''re here to support you and will get back to you shortly with an update on your application status!', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi there! I just realized that the Senior PM role at Swiggy I applied for has disappeared from your site. This is making me really anxious—does this mean the position is filled? Can you help me understand what’s happening?', 'Priya', 'Senior PM', 'Swiggy', 'confused_candidate', 'process_confusion', 'role_no_longer_listed', '["acknowledge", "apologize", "explain_process", "reassure", "set_expectations"]'::jsonb, 'We completely understand your concern and will provide you with an update as soon as possible!', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF, I hope you’re well. I applied for a Product Manager position at Paytm, but I see it’s no longer listed. This has left me feeling really uncertain about my application. Can you clarify what’s going on?', 'Saanvi', 'Product Manager', 'Paytm', 'confused_candidate', 'process_confusion', 'role_no_longer_listed', '["acknowledge", "apologize", "clarify", "reassure", "show_empathy"]'::jsonb, 'Your concerns are valid, and we appreciate your patience as we look into this for you!', 'easy', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team, I just received an offer from Zepto for the Senior PM position, but they want me to join immediately. I have a notice period of 2 months at my current job, and I''m really anxious about how to handle this. Any advice on how I can negotiate this with them? Thanks!', 'Aarav', 'Senior PM', 'Zepto', 'concerned_candidate', 'offer_issue', 'notice_period_issue', '["acknowledge", "show_empathy", "clarify", "reassure", "provide_timeline"]'::jsonb, 'We understand your situation, and we''ll work together to help you communicate your notice period clearly to Zepto while exploring possible solutions.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF team, I’m thrilled to get an offer from Razorpay for the Principal PM role, but they need someone to start right away. Unfortunately, I’m stuck with a 3-month notice period and I’m worried I might lose this opportunity. What should I do?', 'Divya', 'Principal PM', 'Razorpay', 'concerned_candidate', 'offer_issue', 'notice_period_issue', '["acknowledge", "apologize", "show_empathy", "explain_process", "set_expectations"]'::jsonb, 'We totally empathize with your situation and will support you in crafting a message to Razorpay to communicate your notice period and discuss potential flexibility.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I''m excited about the offer from CRED for the Senior PM position, but they want me to join immediately. I’m currently bound by a 2-month notice period, and I feel nervous about negotiating this. How can I approach this?', 'Neha', 'Senior PM', 'CRED', 'concerned_candidate', 'offer_issue', 'notice_period_issue', '["acknowledge", "reassure", "show_empathy", "clarify", "provide_timeline"]'::jsonb, 'We understand your concern, and we''re here to assist you in navigating this situation with CRED, ensuring you feel confident in your approach.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('I can''t believe the candidate we agreed on for the Senior PM position at Zomato didn’t even show up for the interview. This is incredibly frustrating! We need dependable candidates, and this is not the first time this has happened. Can you please look into this?', 'Riya Sharma', 'Senior PM', 'Zomato', 'angry_client', 'general', 'client_candidate_no_show', '["acknowledge", "apologize", "clarify", "show_empathy"]'::jsonb, 'We''ll investigate this matter and ensure better communication with candidates moving forward.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('I''m really disappointed that the candidate for the PM Lead role at Swiggy didn’t attend their scheduled interview. We were looking forward to discussing potential opportunities with them. Can you help figure out what went wrong?', 'Amit Verma', 'PM Lead', 'Swiggy', 'angry_client', 'general', 'client_candidate_no_show', '["acknowledge", "apologize", "reassure", "provide_timeline", "show_empathy"]'::jsonb, 'I hear your frustration, and we’ll ensure candidates are more reliable in the future.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('I’m really frustrated that the candidate you referred for the Senior PM role at Meesho didn’t show up at all for the interview. This lack of professionalism is disappointing, and it’s making it hard for us to move forward. Can we discuss this?', 'Sneha Patel', 'Senior PM', 'Meesho', 'angry_client', 'general', 'client_candidate_no_show', '["acknowledge", "apologize", "explain_process", "show_empathy"]'::jsonb, 'We value your feedback and will improve our candidate vetting process to avoid this in the future.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey TPF team, I''m really frustrated with the candidates you’ve been sending us for the Senior PM role at BharatPe. They don’t seem to have the right experience or skills we’re looking for, and it’s slowing down our hiring process. Can we please have a chat to align on exactly what we need?', 'Ananya', 'Senior PM', 'BharatPe', 'professional_client', 'general', 'client_profile_mismatch', '["acknowledge", "show_empathy", "clarify", "reassure", "set_expectations"]'::jsonb, 'We appreciate your feedback, Ananya, and we''ll work closely with you to refine our search and ensure we align with your expectations moving forward.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi there, I wanted to reach out because the candidates we’ve been receiving for the Principal PM position at CRED just aren’t hitting the mark. It’s becoming a bit frustrating since we’re eager to fill this role. Can we set up a meeting to discuss what’s going wrong?', 'Rahul', 'Principal PM', 'CRED', 'professional_client', 'general', 'client_profile_mismatch', '["acknowledge", "apologize", "explain_process", "reassure", "show_empathy"]'::jsonb, 'Thank you for bringing this to our attention, Rahul; we’re committed to finding the right fit and would love to discuss specifics with you to improve our candidate selection.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I’m reaching out because the candidates for the Senior PM role at Razorpay aren''t quite what we expected. We’re really looking for someone with more hands-on experience, and I’m feeling a bit concerned about the quality of applicants. Can we talk soon?', 'Priya', 'Senior PM', 'Razorpay', 'professional_client', 'general', 'client_profile_mismatch', '["acknowledge", "show_empathy", "clarify", "reassure", "set_expectations"]'::jsonb, 'I completely understand your concerns, Priya, and I assure you that we will take immediate steps to better align our candidate recommendations with your needs.', 'hard', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hey Team, I hope you’re doing well! I’ve been eagerly waiting for my performance review feedback for quite some time now, and it’s starting to make me anxious. Could you please let me know if there’s a timeline for when I might receive it? I’m really looking forward to understanding my role better and how I can contribute more effectively.', 'Riya Sharma', 'Community Manager', 'Zomato', 'concerned_candidate', 'delay', 'internal_team_delayed_feedback', '["acknowledge", "show_empathy", "provide_timeline", "set_expectations"]'::jsonb, 'We understand your concern, Riya, and are actively working to provide you with the feedback you need soon — thank you for your patience!', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF Team, I hope everything is great! It’s been a few weeks since I’ve been waiting for clarity on my role and feedback from my last review. I’m feeling a bit lost and would really appreciate any updates you could share. Thanks for all your support!', 'Arjun Mehta', 'Talent Associate', 'Paytm', 'concerned_candidate', 'delay', 'internal_team_delayed_feedback', '["acknowledge", "reassure", "explain_process", "set_expectations"]'::jsonb, 'We truly appreciate your patience, Arjun, and we''re working on getting back to you with clarity shortly — hang tight!', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello Team, I hope all is well with you! I wanted to reach out regarding the performance review feedback I’ve been expecting for some time now. It’s been hard not knowing where I stand, and I’d love any info or timeline on when I can expect to hear back. Thank you!', 'Nisha Rao', 'Operations Manager', 'Swiggy', 'concerned_candidate', 'delay', 'internal_team_delayed_feedback', '["acknowledge", "clarify", "show_empathy", "provide_timeline"]'::jsonb, 'We hear you, Nisha, and are committed to providing you with the feedback soon — thank you for your understanding!', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi TPF team, I hope you''re doing well! I applied for the Product Manager position at Zepto a few months ago but unfortunately didn’t get through. I’m really passionate about the role and have been working on enhancing my skills since then. Would my application be reconsidered if I reapply? Thank you for your guidance!', 'Riya Sharma', 'Product Manager', 'Zepto', 'concerned_candidate', 'feedback_request', 'candidate_reapplying_after_rejection', '["acknowledge", "show_empathy", "clarify", "reassure", "explain_process"]'::jsonb, 'Absolutely, Riya! We appreciate your determination and would love to see your new application; it reflects your growth and passion.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hello TPF team, I hope you’re all doing great! I had applied for the Senior PM role at Swiggy a few months back but didn’t make it through. I’ve taken some courses to strengthen my skills in the meantime and I’m eager to know if I can be considered again for similar roles. Thank you!', 'Aarav Mehta', 'Senior PM', 'Swiggy', 'concerned_candidate', 'feedback_request', 'candidate_reapplying_after_rejection', '["acknowledge", "show_empathy", "reassure", "provide_timeline", "set_expectations"]'::jsonb, 'Hi Aarav, we love to see candidates who are dedicated to growth! Please feel free to reapply, and we''ll make sure to review your application thoroughly.', 'medium', TRUE);
INSERT INTO scenarios (message, sender_name, role_applied, company_name, tone, category, situation_type, expected_points, ideal_response_tone, difficulty, active) VALUES ('Hi team, I hope everything is going well! I had previously applied for a Product Manager position at CRED but was not selected. Since then, I have gained more experience and insights, and I would love to know if I could be reconsidered if I reapply. Thanks for your help!', 'Priya Kapoor', 'Product Manager', 'CRED', 'concerned_candidate', 'feedback_request', 'candidate_reapplying_after_rejection', '["acknowledge", "show_empathy", "clarify", "reassure", "explain_process"]'::jsonb, 'Hi Priya! Your commitment to growth is impressive, and we would be happy to consider your reapplication; just let us know when you’re ready!', 'medium', TRUE);

-- Sanity check
SELECT count(*) AS users FROM users;
SELECT count(*) AS scenarios FROM scenarios;
